# -*- coding: utf-8 -*-
"""Ai YT Summarizer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13zUhUM5EOlTw2ZkzNpE3I5JCFo-wBhlf
"""

# Installing necessary libraries and packages-
!pip install -q transformers
!pip install -q youtube_transcript_api

# Importing the libraries needed-
from transformers import pipeline
from youtube_transcript_api import YouTubeTranscriptApi

youtube_video = "Paste the link of your youtube video here"

video_id = youtube_video.split("=")[1]

from IPython.display import YouTubeVideo
YouTubeVideo(video_id)

YouTubeTranscriptApi.get_transcript(video_id)
transcript = YouTubeTranscriptApi.get_transcript(video_id)

result = ""
for i in transcript:
    result += ' ' + i['text']
print(len(result))

summarizer = pipeline('summarization')

num_iters = int(len(result)/1000)
summarized_text = []
for i in range(0, num_iters + 1):
  start = 0
  start = i * 1000
  end = (i + 1) * 1000
  out = summarizer(result[start:end])
  out = out[0]
  out = out['summary_text']
  summarized_text.append(out)

print(summarized_text)

str(summarized_text)

import textwrap

consumer_friendly_text = ""

for summary in summarized_text:
    consumer_friendly_text += "\n".join(textwrap.wrap(summary, width=80)) + "\n\n"

print(consumer_friendly_text)